DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler

DATASETS:
  OPEN_WORLD_INTERPRETATION: false
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  RETRIEVAL_AUGMENTATION: None
  TEST: ("isaid_test",)
  TRAIN: ("skysa_graph_train",)

INPUT:
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: true
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE: (384, 384)
    TYPE: absolute
  DATASET_MAPPER_NAME: skysense_o_dataset_mapper
  FORMAT: RGB
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 2560
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: 384
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
  SIZE_DIVISIBILITY: 384

MODEL:
  CLIP_CFG_PATH: "skysense_o/modeling/backbone/clip_config.yml"
  CLIP_CKPT_PATH: "pretrain/skysense_clip.ckpt"
  CLIP_PIXEL_MEAN: [123.675, 116.280, 103.530]
  CLIP_PIXEL_STD: [58.395, 57.120, 57.375]
  DEVICE: cuda
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_ON: false
  META_ARCHITECTURE: SkySenseO
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  PROMPT_ENSEMBLE: false
  PROMPT_ENSEMBLE_TYPE: remote_sensing
  SEM_SEG_HEAD:
    APPEARANCE_GUIDANCE_DIM: 1024
    APPEARANCE_GUIDANCE_PROJ_DIM: 128
    ATTENTION_TYPE: linear
    CLIP_FINETUNE: attention
    CLIP_PRETRAINED: Skysense
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
    FEATURE_RESOLUTION: [24, 24]
    HIDDEN_DIMS: 128
    IGNORE_VALUE: 65535
    IN_FEATURES: ["res2", "res3", "res4"]
    NAME: SkySenseOHead
    NUM_CLASSES: 171
    NUM_HEADS: 4
    NUM_LAYERS: 2
    POOLING_SIZES: [2, 2]
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEST_CLASS_JSON: datasets/coco.json
    TEXT_GUIDANCE_DIM: 1024
    TEXT_GUIDANCE_PROJ_DIM: 128
    TRAIN_CLASS_JSON: datasets/coco.json
    WINDOW_SIZES: 12
  SIZE_DIVISIBILITY: 32
  SWIN:
    APE: false
    ATTN_DROP_RATE: 0.0
    DEPTHS: [2, 2, 6, 2]
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 96
    MLP_RATIO: 4.0
    NUM_HEADS: [3, 6, 12, 24]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    PATCH_NORM: true
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 224
    QKV_BIAS: true
    QK_SCALE: null
    WINDOW_SIZE: 7
  WEIGHTS: ''

OUTPUT_DIR: output/skysense_o_debug/skysa_graph
REGION_CONTRAST_WEIGHT: 0.4
REGULAR_WEIGHT: 0.4
SEED: 12345

SOLVER:
  AMP:
    ENABLED: false
  BACKBONE_MULTIPLIER: 0.0
  BASE_LR: 0.0002
  BASE_LR_END: 0.0
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 0.01
    ENABLED: true
    NORM_TYPE: 2.0
  CLIP_MULTIPLIER: 0.01
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 80000
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  STEPS: [30000]
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0

TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES: [400, 500, 600, 700, 800, 900, 1000, 1100, 1200]
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 8
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
  SLIDING_WINDOW: false

VERSION: 2
CUDNN_BENCHMARK: true
