_BASE_: base.yaml
DATASETS:
  TRAIN: ("skysa_graph_train",)
  TEST: ('isaid_test',)
  RETRIEVAL_AUGMENTATION: False
  OPEN_WORLD_INTERPRETATION: False
REGION_CONTRAST_WEIGHT: 0.0
PIXEL_CONTRAST_WEIGHT: 1.0
REGULAR_WEIGHT: 0.0
CONTRAST_SCALE: 1
SOLVER:
  TEST_IMS_PER_BATCH: 1
  BASE_LR: 0.0002
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 4000
OUTPUT_DIR: "./output/default"
MODEL:
  SEM_SEG_HEAD:
    CLIP_FINETUNE: "full"
SAMPLING_HYPER: [1, 7, 9, 10]
TEXT_BATCH: 100